name: Build

on: 
  push:
    branches: [main]

jobs:
  build:  
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Xcode command line tools 
        run: xcode-select --install
        
      - name: Build with Xcode
        run: |
          xcodebuild archive -project Code.xcodeproj -scheme Code -archivePath Code.xcarchive
          xcodebuild -exportArchive -archivePath Code.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist

      - name: Upload build artifact 
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: Code.ipa
